name: SSE CI/CD

on: [push]

jobs:
  Style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install clang-format"
        run: sudo apt install clang-format -y
      - name: "Run clang-format"
        run: clang-format -i src/*.hpp src/*.cpp tests/*.cpp --dry-run --Werror
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies for C++"
        run: sudo apt update && sudo apt install cmake gcc libeigen3-dev libyaml-cpp-dev libboost-all-dev
      - name: "Create build folder"
        run: mkdir build
      - name: "Run cmake"
        working-directory: ./build
        run: cmake ..
      - name: "Build make"
        working-directory: ./build
        run: make
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies for C++"
        run: sudo apt-get install cmake libyaml-cpp-dev libeigen3-dev libboost-test-dev
      - name: "Cmake"
        run: mkdir build && cd build && cmake ..
      - name: "Make"
        run: cd build && make
      - name: "Test"
        run: cd build && make test